[server]
url = 'http://localhost:3000'

[scan]
extensions = ['ts']
use_ignore_files = [
  '.gitignore',
  '.dockerignore',
  '.dryignore'
]

[scan.similarity]
threshold = 0.8
limit = 10

[[scan.patterns]]
extensions = [
  'ts',
  'tsx',
  'js',
  'jsx'
]
include = [
  'function\s+(\w+)\s*\(',
  'const\s+(\w+)\s*=\s*\([^)]*\)\s*=>',
  '(\w+):\s*function\s*\(',
  'if\s*\([^)]*\)\s*{',
  'for\s*\([^)]*\)\s*{'
]
