[server]
url = "http://localhost:3000"

[scan]
use_ignore_files = [".gitignore", ".dockerignore", ".dryignore"]

[scan.similarity]
threshold = 0.6
limit = 10

[scan.languages.ts]
include = [
  'function\s+(\w+)\s*\(',                           # function declarations
  'const\s+(\w+)\s*=\s*\([^)]*\)\s*=>',           # arrow functions
  '(\w+):\s*function\s*\(',                           # object functions
  'if\s*\([^)]*\)\s*{',                            # if cases
  'for\s*\([^)]*\)\s*{',                            # for cases
]
exclude = []
